### ISSUE TITLE
Chatwoot setup script not working

### ISSUE THREAD

**Issue by kshitijkna** [BiteSpeed-Dev/chatwoot#1]
Chatwoot setup script returning errors in aws ec2.

<img width="1680" alt="Screenshot 2022-05-22 at 3 22 07 AM" src="https://user-images.githubusercontent.com/43352138/169670139-656017aa-9d1c-4789-afdd-c02eb5fdeb19.png">
<img width="1680" alt="Screenshot 2022-05-22 at 3 18 00 AM" src="https://user-images.githubusercontent.com/43352138/169670144-243b814e-7478-4e77-87d9-da4bc18831df.png">
<img width="1680" alt="Screenshot 2022-05-22 at 3 17 45 AM" src="https://user-images.githubusercontent.com/43352138/169670145-1e571ff0-2255-4168-8b70-31b3f916121c.png">

I am following https://www.chatwoot.com/docs/self-hosted/deployment/aws#install-chatwoot step 11. Step 10 I didn't make any change and am just selecting no for the options asked by the script.

**Comment by kshitijkna** [comment]
@sojan-official Could you please help with this?

**Comment by vishnu-narayanan** [comment]
@kshitijkna Looks like you are running this on 22.04 and `ruby-3.0.2` is not available. As of now, we are testing/verifying this on Ubuntu 20.04  and would recommend you to try this on `20.04`.

Could you try this again on `20.04`?
