### ISSUE TITLE
504 Gateway Time-out when trying to reach the self hosted chatwoot server

### ISSUE THREAD

**Issue by kshitijkna** [BiteSpeed-Dev/chatwoot#2]
@sojan-official @vishnu-narayanan 
I was able to set up and run the migrations on the main Shatwoot server, but I am still very confused about how to access it. I tried using the installation with and without domain and ssh set up, tried adding a A record for the ALB in route 53 and still nothing worked, it keeps giving "504 Gateway Time-out" on both the configured domain (cs.bitespeed.co) and the domain of ALB (http://chatwoot-loadbalancer-227898534.us-east-2.elb.amazonaws.com/)

While trying to debug, I found out that the ALB was showing the EC2 instance as unhealthy in the target groups. I also noticed that chatwoot listens on port 3000 but in the loadbalancer security group setup its not mentioned to open the 3000 port, so it could be linked to that. Also it was mention in [here](https://www.chatwoot.com/docs/self-hosted/deployment/aws#application-load-balancer-alb) in 2.vi.b. to add /api endpoint but I am not sure what to do there. 
![Screenshot 2022-05-25 at 1 41 43 AM](https://user-images.githubusercontent.com/43352138/170123581-016b4f71-2830-41de-a05e-326bc999ac9c.png)

Could you please help resolve this?

**Comment by kshitijkna** [comment]
@vishnu-narayanan The /api has already been added as the health check endpoint

Could it be because the port 3000 isn't open on the chatwoot server? Because the security group on it (chatwoot-loadbalancer-sg) has only ports 80 and 443 open? I am not able to directly hit the chatwoot server also as it is in a private vpc without a public IP, how do you suggest I try hitting the main server in this case?

![Screenshot 2022-05-25 at 12 54 13 PM](https://user-images.githubusercontent.com/43352138/170204717-3d181918-312b-4a55-a338-135404957b2e.png)

**Comment by vishnu-narayanan** [comment]
@kshitijkna Could you try adding an `all-traffic` inbound rule to the `chatwoot-loadbalancer-sg` for the time being and see if that helps?  Meanwhile, we will debug and get back to you on this.

**Comment by kshitijkna** [comment]
@vishnu-narayanan Added the all-traffic inbound rule but still facing the same issue. Unhealthy on ALB and not able to make curl requests to the main server through the bastion servers.

**Comment by vishnu-narayanan** [comment]
@kshitijkna Would you be able to share read-only access to this AWS account so that I can take a look? If that is too much of an ask, let's get into a call tomorrow.

**Comment by kshitijkna** [comment]
@vishnu-narayanan Yeah let's get on a call as I can get a better understanding through that and also I am not sure how exactly to create a read-only IAM role without missing out some permission on which we will have to go back n forth. Does sometime tomorrow from 12:30 pm to 3 pm work for you? Or else we could do anytime post 8 pm?

**Comment by vishnu-narayanan** [comment]
@kshitijkna Missed the message. Anytime before 7.30 would have been fine. Would 11-1130 pm work for you? If not, let's catch up on Monday as I am travelling tomorrow.

**Comment by kshitijkna** [comment]
@vishnu-narayanan Yeah 11-11:30 pm works for me. Can you send me a calendar invite for the same at kshitij@bitespeed.co?

**Comment by vishnu-narayanan** [comment]
done
